/**
 * plan-readiness-map.ts — M11 additive registry mapping (AM-0019 §14).
 *
 * Cohesive data sub-module of plan-readiness.ts: the canonical
 * requirement→module map for the M11 additive registry plus the cluster
 * lookup. Status is derived honestly at compile time in plan-readiness.ts:
 * every mapped module AND test file must exist in the tree, else the
 * requirement degrades to PARTIAL/GAP. A module hash (SHA-256 of file bytes)
 * is recorded as tree evidence. Never invented: no entry claims COVERED
 * without its modules present.
 */

interface M11Implementation {
  cluster: string;
  /** MATCH = implemented; PARTIAL = implemented but a named condition stays open. */
  status: 'MATCH' | 'PARTIAL';
  /** Paths relative to repo root; existence is probed at compile time. */
  modules: string[];
  /** Test/evidence paths relative to repo root; existence is probed too. */
  tests: string[];
  /** Why the requirement stays PARTIAL when all modules/tests exist. */
  partialReason?: string;
  acceptanceCriteria: string[];
}

export const M11_IMPLEMENTATIONS: Record<string, M11Implementation> = {
  'M11-R11': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/plan-readiness.ts', 'packages/cli/src/commands/plan.ts'],
    tests: ['packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'plan-readiness compiles the 31 effective requirements without a hard-coded count',
      'CLI `plan readiness <plan-id>` atomically writes the 9 projection files (incl. verification-graph.yaml)',
    ],
  },
  'M11-R12': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/plan-readiness.ts'],
    tests: ['packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'autonomy.yaml (readiness_state + authority envelope + decision matrix) generated by plan-readiness',
      'decisions.yaml (recorded reversible defaults + unknowns register) generated by plan-readiness',
    ],
  },
  'M11-R13': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/plan-readiness.ts', 'packages/engine/src/dispatch-ready-set.ts'],
    tests: ['packages/engine/test/dispatch-ready-set.test.ts', 'packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'execution-graph.yaml emits typed cross-stage dependency edges (HARD/SOFT/VERIFY_AFTER/…/EXTERNAL)',
      'dispatch-ready-set computes ready sets over a typed dependency graph with blocking/non-blocking classes',
    ],
  },
  'M11-R14': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/dispatch-ready-set.ts', 'packages/engine/src/controller.ts'],
    tests: ['packages/engine/test/dispatch-ready-set.test.ts', 'packages/engine/test/controller.test.ts'],
    acceptanceCriteria: [
      'max-useful conflict-free ready antichain scheduling without starving independent work',
      'controller.dispatchReadySet executes the readiness dispatch path',
    ],
  },
  'M11-R15': {
    cluster: 'C3',
    status: 'MATCH',
    modules: ['packages/engine/src/worktree-train.ts', 'packages/cli/src/commands/train.ts', 'packages/cli/src/commands/worktree.ts'],
    tests: ['packages/engine/test/worktree-train.test.ts', 'packages/engine/test/worktree-inventory.test.ts'],
    acceptanceCriteria: [
      'per-assignment worktree isolation with leased lifecycle (create/integrate/release)',
      'rolling integration train merges accepted branches in receipt order',
    ],
  },
  'M11-R16': {
    cluster: 'C4',
    status: 'MATCH',
    modules: ['packages/engine/src/resource-broker.ts', 'packages/engine/src/resource-governor.ts'],
    tests: ['packages/engine/test/resource-broker.test.ts', 'packages/engine/test/resource-governor.test.ts'],
    acceptanceCriteria: [
      'global broker multiplexes resource/tool/browser pools under leases',
      'governor enforces pool ceilings and hysteresis from memory/PSI/swap signals',
    ],
  },
  'M11-R17': {
    cluster: 'C5',
    status: 'MATCH',
    modules: ['packages/engine/src/autopilot-m11.ts', 'packages/engine/src/supervisor.ts', 'packages/engine/src/terminal-gate.ts'],
    tests: ['packages/engine/test/autopilot-m11.test.ts', 'packages/engine/test/supervisor.test.ts', 'packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'nonterminal continuation across WAITING_EXTERNAL/WAITING_AUTHORITY/WAITING_RESOURCE/RETRY_SCHEDULED',
      'durable autopilot resumes after crash without duplicate or lost work',
      'terminal-gate blocks terminal claims while required conditions are open',
    ],
  },
  'M11-R18': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/topology-compiler.ts'],
    tests: ['packages/engine/test/topology-compiler.test.ts'],
    acceptanceCriteria: [
      'system-topology.yaml compiled to a typed topology (services/ports/ingress/databases/queues/migrations/journeys)',
      'topology hash + validation produce deterministic output',
    ],
  },
  'M11-R19': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/topology-compiler.ts', 'packages/engine/src/terminal-gate.ts'],
    tests: ['packages/engine/test/topology-compiler.test.ts', 'packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'verifyLayers evaluates the mandatory unit→component→contract→service-integration→deployed-topology chain',
      'terminal gate refuses finalization while required verification layers are skipped',
    ],
  },
  'M11-R20': {
    cluster: 'C7',
    status: 'MATCH',
    modules: ['packages/engine/src/parity-runner.ts', 'packages/engine/src/visual-contracts.ts'],
    tests: ['packages/engine/test/parity-runner.test.ts', 'packages/engine/test/parity-contracts.test.ts'],
    acceptanceCriteria: [
      'paired REF/TGT browser contract with page-lease collision domains',
      'parity runner compiles reference/target diffs and decides verdicts',
    ],
  },
  'M11-R21': {
    cluster: 'C7',
    status: 'MATCH',
    modules: ['packages/engine/src/parity-runner.ts', 'packages/engine/src/parity-pixels.ts', 'packages/engine/src/visual-reducer.ts'],
    tests: ['packages/engine/test/parity-runner.test.ts', 'packages/engine/test/visual-harness.test.ts', 'packages/engine/test/visual-seeded-defect.test.ts'],
    acceptanceCriteria: [
      'pixel-level diff computed without a vision model',
      'visual reducer scores seeded defect matrix and rejects regressions',
    ],
  },
  'M11-R22': {
    cluster: 'C8',
    status: 'PARTIAL',
    partialReason: 'Tier-A convergence implementation present; codex native runtime proof requires external codex runtime — WAITING_EXTERNAL',
    modules: ['platforms/claude/adapter.ts', 'platforms/opencode/adapter.ts', 'platforms/codex/adapter.ts', 'automation/host-attestation.ts'],
    tests: ['platforms/claude/adapter.test.ts', 'platforms/opencode/adapter.test.ts', 'automation/host-attestation.test.ts', 'evals/m11/attestation.py'],
    acceptanceCriteria: [
      'claude/opencode/codex native adapters exist',
      'host attestation binds evidence to exact HEAD',
      'codex runtime convergence proof gated on external codex availability',
    ],
  },
  'M11-R23': {
    cluster: 'C8',
    status: 'MATCH',
    modules: ['platforms/grok/adapter.ts', 'platforms/antigravity/adapter.ts', 'platforms/cursor/adapter.ts', 'packages/engine/src/contracts.ts'],
    tests: ['packages/engine/test/workflow-validation.test.ts', 'evals/m11/antigravity.py'],
    acceptanceCriteria: [
      'CERTIFICATION_REQUIRED_HOSTS = codex/claude/grok/opencode/antigravity enforced by workflow validation',
      'grok/antigravity/cursor adapters define out-of-ownership mutation boundaries (eval-rejected)',
    ],
  },
  'M11-R24': {
    cluster: 'C9',
    status: 'MATCH',
    modules: ['packages/engine/src/terminal-gate.ts', 'packages/engine/src/ledger-activation.ts'],
    tests: ['packages/engine/test/terminal-gate.test.ts', 'packages/engine/test/ledger-activation.test.ts'],
    acceptanceCriteria: [
      'evaluateM11Terminal derives terminal truth from ledger gates, not external tokens',
      'ledger-activation enforces canonical atomic activation and migration',
    ],
  },
  'M11-R25': {
    cluster: 'C9',
    status: 'MATCH',
    modules: ['packages/engine/src/supervisor.ts', 'packages/engine/src/worker-adapter.ts', 'evals/m11'],
    tests: ['packages/engine/test/supervisor.test.ts', 'packages/engine/test/worker-verifier.test.ts', 'evals/m11/aggregation.test.ts'],
    acceptanceCriteria: [
      'subagent-first audit/review with independent verifier/reviewer paths',
      'main-context protection: workers own source edits, main orchestrates/reviews only',
    ],
  },
  'M11-R26': {
    cluster: 'C10',
    status: 'MATCH',
    modules: ['evals/m11', 'evals/m11/runner.py'],
    tests: [
      'packages/engine/test/dispatch-ready-set.test.ts',
      'packages/engine/test/autopilot-m11.test.ts',
      'packages/engine/test/topology-compiler.test.ts',
      'packages/engine/test/parity-runner.test.ts',
      'packages/engine/test/adversarial-closure.test.ts',
      'evals/m11/coverage.py',
    ],
    acceptanceCriteria: [
      'controlled dogfood runs the M11-C10 eval suite (run-m11-evals.py aggregates PASS/FAIL/WAITING_EXTERNAL)',
      'adversarial closure tests reject out-of-ownership mutation and deterministic defects',
    ],
  },
  // ── AM-0020 §14 additive registry (M11-R27..R36) ───────────────────────────
  'M11-R27': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/claim-registry.ts'],
    tests: ['packages/engine/test/claim-registry.test.ts'],
    acceptanceCriteria: [
      'each effective requirement (41) compiles into ≥1 ClaimDefinition with all AM-0020 §2 fields',
      'evaluateClaimFormulas fail-closes: one PARTIAL/CONTRADICTED/stale/capability-invalid subclaim blocks the aggregate',
    ],
  },
  'M11-R28': {
    cluster: 'C9',
    status: 'PARTIAL',
    partialReason: 'evidence provenance + freshness DAG lands with the M11-R28 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/evidence-packet.ts'],
    tests: ['packages/engine/test/evidence-packet.test.ts'],
    acceptanceCriteria: [
      'evidence envelope records claim_ids/candidate_epoch/producer/command/exit_code/hashes/freshness',
      'evidence promotion path PRESENT→PARSEABLE→SEMANTICALLY_VALID→BINDS_FINAL_CANDIDATE→CAPABILITY_VALID→INDEPENDENTLY_REPRODUCED→TERMINAL_ELIGIBLE',
    ],
  },
  'M11-R29': {
    cluster: 'C8',
    status: 'PARTIAL',
    partialReason: 'capability-qualified verdicts land with the M11-R29 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/native-session-adapter.ts'],
    tests: ['packages/engine/test/opencode-adapter.test.ts'],
    acceptanceCriteria: [
      'verdicts are capability-qualified: no-vision review cannot issue visual PASS, Playwright-only evidence cannot issue raw-CDP PASS',
      'model/capability substitution is never silent',
    ],
  },
  'M11-R30': {
    cluster: 'C2',
    status: 'PARTIAL',
    partialReason: 'adversarial counterexample compiler lands with the M11-R30 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/verifier.ts'],
    tests: ['packages/engine/test/worker-verifier.test.ts'],
    acceptanceCriteria: [
      'negative probes generated from plan invariants/topology/domain (finance/concurrency/security/browser/release)',
      'T2/T3 claims require a negative probe unless deterministic proof makes it formally unnecessary',
    ],
  },
  'M11-R31': {
    cluster: 'C9',
    status: 'PARTIAL',
    partialReason: 'reviewer independence + diversity lands with the M11-R31 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/supervisor.ts'],
    tests: ['packages/engine/test/supervisor.test.ts'],
    acceptanceCriteria: [
      'reviewer accepts only its exact claim scope and can never declare the project complete',
      'blind adversarial review precedes reading the worker verdict; conflicts adjudicated, not majority-voted',
    ],
  },
  'M11-R32': {
    cluster: 'C4',
    status: 'PARTIAL',
    partialReason: 'immutable candidate verification lands with the M11-R32 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/plan-identity.ts'],
    tests: ['packages/engine/test/plan-identity.test.ts'],
    acceptanceCriteria: [
      'final verification binds an immutable CandidateEpoch; dirty worktree cannot be the terminal candidate',
      'source/config/lockfile/migration change creates a new epoch and invalidates only dependent proof',
    ],
  },
  'M11-R33': {
    cluster: 'C6',
    status: 'PARTIAL',
    partialReason: 'cross-artifact consistency validator lands with the M11-R33 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/verifier.ts'],
    tests: ['packages/engine/test/worker-verifier.test.ts'],
    acceptanceCriteria: [
      'engine validates test totals vs summaries vs report, ledger status vs report status, evidence time vs candidate epoch',
      'PARTIAL/HIGH_DIFF/SKIPPED/UNVERIFIED records cannot be hidden by an aggregate PASS',
    ],
  },
  'M11-R34': {
    cluster: 'C10',
    status: 'PARTIAL',
    partialReason: 'machine-generated terminal reporting lands with the M11-R34 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/terminal-gate.ts'],
    tests: ['packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'terminal report generated from the canonical ledger with claim coverage, evidence maturity, open findings, terminal formula result',
      'report compiler fails closed on stale evidence, missing capability, blocking finding, or identity mismatch',
    ],
  },
  'M11-R35': {
    cluster: 'C10',
    status: 'PARTIAL',
    partialReason: 'seeded false-green/false-reject evaluation lands with the M11-R35 worktree — WAITING_EXTERNAL',
    modules: ['evals/m11', 'evals/m11/coverage.py'],
    tests: ['evals/m11/coverage.py'],
    acceptanceCriteria: [
      '100% seeded false-green fixtures blocked; 100% known-good fixtures reach correct status',
      'zero self-review terminal path, zero capability-invalid PASS, zero terminal report unbound to final candidate',
    ],
  },
  'M11-R36': {
    cluster: 'C9',
    status: 'PARTIAL',
    partialReason: 'claim calibration telemetry lands with the M11-R36 worktree — WAITING_EXTERNAL',
    modules: ['packages/engine/src/telemetry.ts'],
    tests: ['packages/engine/test/telemetry.test.ts'],
    acceptanceCriteria: [
      'records worker self-PASS later rejected, reviewer ACCEPT later rejected, false rejection overturned, defect escape by model/provider/domain',
      'model reputation alone never authorizes a verdict; calibration, capability and exact evidence do',
    ],
  },
};

export function clusterForM11(id: string): string {
  return M11_IMPLEMENTATIONS[id]?.cluster ?? 'C10';
}
