/**
 * plan-readiness-map.ts — M11 additive registry mapping (AM-0019 §14).
 *
 * Cohesive data sub-module of plan-readiness.ts: the canonical
 * requirement→module map for the M11 additive registry plus the cluster
 * lookup. Status is derived honestly at compile time in plan-readiness.ts:
 * every mapped module AND test file must exist in the tree, else the
 * requirement degrades to PARTIAL/GAP. A module hash (SHA-256 of file bytes)
 * is recorded as tree evidence. Never invented: no entry claims COVERED
 * without its modules present.
 */

interface M11Implementation {
  cluster: string;
  /**
   * MATCH = implemented; PARTIAL = implemented but a named condition stays open;
   * SUPERSEDED = the owner removed this scope, so absent modules are expected rather
   * than a gap. Use `partialReason` to say what replaced it.
   */
  status: 'MATCH' | 'PARTIAL' | 'SUPERSEDED';
  /** Paths relative to repo root; existence is probed at compile time. */
  modules: string[];
  /** Test/evidence paths relative to repo root; existence is probed too. */
  tests: string[];
  /** Why the requirement stays PARTIAL when all modules/tests exist. */
  partialReason?: string;
  acceptanceCriteria: string[];
}

export const M11_IMPLEMENTATIONS: Record<string, M11Implementation> = {
  'M11-R11': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/plan-readiness.ts', 'packages/cli/src/commands/plan.ts'],
    tests: ['packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'plan-readiness compiles the 31 effective requirements without a hard-coded count',
      'CLI `plan readiness <plan-id>` atomically writes the 9 projection files (incl. verification-graph.yaml)',
    ],
  },
  'M11-R12': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/plan-readiness.ts'],
    tests: ['packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'autonomy.yaml (readiness_state + authority envelope + decision matrix) generated by plan-readiness',
      'decisions.yaml (recorded reversible defaults + unknowns register) generated by plan-readiness',
    ],
  },
  'M11-R13': {
    cluster: 'C2',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: typed ready-set dispatch replaced by the sequential runner queue (see .agent/plans/harness-v3-rearchitecture/requirements.yaml R-014)',
    modules: ['packages/engine/src/plan-readiness.ts', 'packages/engine/src/dispatch-ready-set.ts'],
    tests: [ 'packages/engine/test/plan-readiness.test.ts'],
    acceptanceCriteria: [
      'execution-graph.yaml emits typed cross-stage dependency edges (HARD/SOFT/VERIFY_AFTER/…/EXTERNAL)',
      'dispatch-ready-set computes ready sets over a typed dependency graph with blocking/non-blocking classes',
    ],
  },
  'M11-R14': {
    cluster: 'C2',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: controller/dispatch scheduling replaced by runner/loop.ts (R-014)',
    modules: ['packages/engine/src/dispatch-ready-set.ts', 'packages/engine/src/controller.ts'],
    tests: [ 'packages/engine/test/controller.test.ts'],
    acceptanceCriteria: [
      'max-useful conflict-free ready antichain scheduling without starving independent work',
      'controller.dispatchReadySet executes the readiness dispatch path',
    ],
  },
  'M11-R15': {
    cluster: 'C3',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: worktree isolation and the integration train are unnecessary for a sequential runner (R-016)',
    modules: ['packages/engine/src/worktree-train.ts', 'packages/cli/src/commands/train.ts', 'packages/cli/src/commands/worktree.ts'],
    tests: [ 'packages/engine/test/worktree-inventory.test.ts'],
    acceptanceCriteria: [
      'per-assignment worktree isolation with leased lifecycle (create/integrate/release)',
      'rolling integration train merges accepted branches in receipt order',
    ],
  },
  'M11-R16': {
    cluster: 'C4',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: resource broker/governor arbitrated a worker pool that never existed (R-018)',
    modules: ['packages/engine/src/resource-broker.ts', 'packages/engine/src/resource-governor.ts'],
    tests: [ 'packages/engine/test/resource-governor.test.ts'],
    acceptanceCriteria: [
      'global broker multiplexes resource/tool/browser pools under leases',
      'governor enforces pool ceilings and hysteresis from memory/PSI/swap signals',
    ],
  },
  'M11-R17': {
    cluster: 'C5',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: dual autopilot replaced by runner/loop.ts with bounded repair (R-015)',
    modules: ['packages/engine/src/autopilot-m11.ts', 'packages/engine/src/supervisor.ts', 'packages/engine/src/terminal-gate.ts'],
    tests: [ 'packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'nonterminal continuation across WAITING_EXTERNAL/WAITING_AUTHORITY/WAITING_RESOURCE/RETRY_SCHEDULED',
      'durable autopilot resumes after crash without duplicate or lost work',
      'terminal-gate blocks terminal claims while required conditions are open',
    ],
  },
  'M11-R18': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/topology-compiler.ts'],
    tests: ['packages/engine/test/topology-compiler.test.ts'],
    acceptanceCriteria: [
      'system-topology.yaml compiled to a typed topology (services/ports/ingress/databases/queues/migrations/journeys)',
      'topology hash + validation produce deterministic output',
    ],
  },
  'M11-R19': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/topology-compiler.ts', 'packages/engine/src/terminal-gate.ts'],
    tests: ['packages/engine/test/topology-compiler.test.ts', 'packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'verifyLayers evaluates the mandatory unit→component→contract→service-integration→deployed-topology chain',
      'terminal gate refuses finalization while required verification layers are skipped',
    ],
  },
  'M11-R20': {
    cluster: 'C7',
    status: 'MATCH',
    modules: ['packages/engine/src/parity-runner.ts', 'packages/engine/src/visual-contracts.ts'],
    tests: ['packages/engine/test/parity-runner.test.ts', 'packages/engine/test/parity-contracts.test.ts'],
    acceptanceCriteria: [
      'paired REF/TGT browser contract with page-lease collision domains',
      'parity runner compiles reference/target diffs and decides verdicts',
    ],
  },
  'M11-R21': {
    cluster: 'C7',
    status: 'MATCH',
    modules: ['packages/engine/src/parity-runner.ts', 'packages/engine/src/parity-pixels.ts', 'packages/engine/src/visual-reducer.ts'],
    tests: ['packages/engine/test/parity-runner.test.ts', 'packages/engine/test/visual-harness.test.ts', 'packages/engine/test/visual-seeded-defect.test.ts'],
    acceptanceCriteria: [
      'pixel-level diff computed without a vision model',
      'visual reducer scores seeded defect matrix and rejects regressions',
    ],
  },
  'M11-R22': {
    cluster: 'C8',
    status: 'MATCH',
    modules: ['platforms/claude/adapter.ts', 'platforms/opencode/adapter.ts', 'platforms/codex/adapter.ts', 'automation/host-attestation.ts'],
    tests: ['platforms/claude/adapter.test.ts', 'platforms/opencode/adapter.test.ts', 'automation/host-attestation.test.ts', 'evals/m11/attestation.py'],
    acceptanceCriteria: [
      'claude/opencode/codex native adapters exist',
      'host attestation binds evidence to exact HEAD',
      'codex native runtime proof bound by live attestation to exact HEAD',
    ],
  },
  'M11-R23': {
    cluster: 'C8',
    status: 'MATCH',
    modules: ['platforms/grok/adapter.ts', 'platforms/antigravity/adapter.ts', 'platforms/cursor/adapter.ts', 'packages/engine/src/contracts.ts'],
    tests: ['packages/engine/test/workflow-validation.test.ts', 'evals/m11/antigravity.py'],
    acceptanceCriteria: [
      'CERTIFICATION_REQUIRED_HOSTS = codex/claude/grok/opencode/antigravity enforced by workflow validation',
      'grok/antigravity/cursor adapters define out-of-ownership mutation boundaries (eval-rejected)',
    ],
  },
  'M11-R24': {
    cluster: 'C9',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: ledger-activation and its global contract hash were the source of HASH-001; replaced by the flat requirements ledger (R-017)',
    modules: ['packages/engine/src/terminal-gate.ts', 'packages/engine/src/ledger-activation.ts'],
    tests: ['packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'evaluateM11Terminal derives terminal truth from ledger gates, not external tokens',
      'ledger-activation enforces canonical atomic activation and migration',
    ],
  },
  'M11-R25': {
    cluster: 'C9',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: supervisor pool replaced by one headless process per task (R-014)',
    modules: ['packages/engine/src/supervisor.ts', 'packages/engine/src/worker-adapter.ts', 'evals/m11'],
    tests: [ 'packages/engine/test/worker-verifier.test.ts', 'evals/m11/aggregation.test.ts'],
    acceptanceCriteria: [
      'subagent-first audit/review with independent verifier/reviewer paths',
      'main-context protection: workers own source edits, main orchestrates/reviews only',
    ],
  },
  'M11-R26': {
    cluster: 'C10',
    status: 'MATCH',
    modules: ['evals/m11', 'evals/m11/runner.py'],
    tests: [
      'packages/engine/test/topology-compiler.test.ts',
      'packages/engine/test/parity-runner.test.ts',
      'packages/engine/test/adversarial-closure.test.ts',
      'evals/m11/coverage.py',
    ],
    acceptanceCriteria: [
      'controlled dogfood runs the M11-C10 eval suite (run-m11-evals.py aggregates PASS/FAIL/WAITING_EXTERNAL)',
      'adversarial closure tests reject out-of-ownership mutation and deterministic defects',
    ],
  },
  // ── AM-0020 §14 additive registry (M11-R27..R36) ───────────────────────────
  'M11-R27': {
    cluster: 'C1',
    status: 'MATCH',
    modules: ['packages/engine/src/claim-registry.ts'],
    tests: ['packages/engine/test/claim-registry.test.ts'],
    acceptanceCriteria: [
      'each effective requirement (41) compiles into ≥1 ClaimDefinition with all AM-0020 §2 fields',
      'evaluateClaimFormulas fail-closes: one PARTIAL/CONTRADICTED/stale/capability-invalid subclaim blocks the aggregate',
    ],
  },
  'M11-R28': {
    cluster: 'C9',
    status: 'MATCH',
    modules: ['packages/engine/src/evidence-dag.ts', 'packages/engine/src/evidence-packet.ts'],
    tests: ['packages/engine/test/evidence-dag.test.ts', 'packages/engine/test/evidence-packet.test.ts', 'evals/m11/evidence-aggregation.test.ts'],
    acceptanceCriteria: [
      'evidence envelope records claim_ids/candidate_epoch/producer/command/exit_code/hashes/freshness',
      'evidence promotion path PRESENT→PARSEABLE→SEMANTICALLY_VALID→BINDS_FINAL_CANDIDATE→CAPABILITY_VALID→INDEPENDENTLY_REPRODUCED→TERMINAL_ELIGIBLE',
      'freshness DAG invalidation stales only dependents; claim maturity derives from the DAG via promotion',
    ],
  },
  'M11-R29': {
    cluster: 'C8',
    status: 'MATCH',
    modules: ['packages/engine/src/review-receipt.ts', 'packages/engine/src/native-session-adapter.ts'],
    tests: ['packages/engine/test/review-receipt.test.ts'],
    acceptanceCriteria: [
      'verdicts are capability-qualified: no-vision review cannot issue visual PASS, Playwright-only evidence cannot issue raw-CDP PASS',
      'model/capability substitution is never silent',
      'terminal eligibility per tier requires a valid, fresh ReviewReceipt set (AM-0020 §5–6)',
    ],
  },
  'M11-R30': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/adversarial-compiler.ts'],
    tests: ['packages/engine/test/adversarial-compiler.test.ts'],
    acceptanceCriteria: [
      'negative probes generated from plan invariants/topology/domain (finance/concurrency/security/browser/release)',
      'T2/T3 claims require a negative probe unless deterministic proof makes it formally unnecessary',
    ],
  },
  'M11-R31': {
    cluster: 'C9',
    status: 'MATCH',
    modules: ['packages/engine/src/review-independence.ts'],
    tests: ['packages/engine/test/review-independence.test.ts'],
    acceptanceCriteria: [
      'reviewer accepts only its exact claim scope and can never declare the project complete',
      'blind adversarial review precedes reading the worker verdict; conflicts adjudicated, not majority-voted',
    ],
  },
  'M11-R32': {
    cluster: 'C4',
    status: 'MATCH',
    modules: ['packages/engine/src/candidate-epoch.ts'],
    tests: ['packages/engine/test/candidate-epoch.test.ts'],
    acceptanceCriteria: [
      'final verification binds an immutable CandidateEpoch; dirty worktree cannot be the terminal candidate',
      'source/config/lockfile/migration change creates a new epoch and invalidates only dependent proof',
    ],
  },
  'M11-R33': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/artifact-consistency.ts'],
    tests: ['packages/engine/test/artifact-consistency.test.ts'],
    acceptanceCriteria: [
      'engine validates test totals vs summaries vs report, ledger status vs report status, evidence time vs candidate epoch',
      'PARTIAL/HIGH_DIFF/SKIPPED/UNVERIFIED records cannot be hidden by an aggregate PASS',
    ],
  },
  'M11-R34': {
    cluster: 'C10',
    status: 'MATCH',
    modules: ['packages/engine/src/terminal-gate.ts'],
    tests: ['packages/engine/test/terminal-report.test.ts', 'packages/engine/test/terminal-gate.test.ts'],
    acceptanceCriteria: [
      'terminal report generated from the canonical ledger with claim coverage, evidence maturity, open findings, terminal formula result',
      'report compiler fails closed on stale evidence, missing capability, blocking finding, or identity mismatch',
    ],
  },
  'M11-R35': {
    cluster: 'C10',
    status: 'MATCH',
    modules: ['evals/m11/false_green.py'],
    tests: ['evals/m11/false_green.py', 'packages/engine/test/false-green-reject.test.ts'],
    acceptanceCriteria: [
      '100% seeded false-green fixtures blocked; 100% known-good fixtures reach correct status',
      'zero self-review terminal path, zero capability-invalid PASS, zero terminal report unbound to final candidate',
    ],
  },
  'M11-R36': {
    cluster: 'C9',
    status: 'MATCH',
    modules: ['packages/engine/src/calibration.ts'],
    tests: ['packages/engine/test/calibration.test.ts'],
    acceptanceCriteria: [
      'records worker self-PASS later rejected, reviewer ACCEPT later rejected, false rejection overturned, defect escape by model/provider/domain',
      'model reputation alone never authorizes a verdict; calibration, capability and exact evidence do',
    ],
  },
  // ── AM-0021 §11 additive registry (M11-R37..R50) ───────────────────────────
  'M11-R37': {
    cluster: 'C5',
    status: 'MATCH',
    modules: ['packages/engine/src/main-run-capsule.ts', 'packages/engine/src/token-attribution.ts'],
    tests: ['packages/engine/test/main-run-capsule.test.ts', 'packages/engine/test/token-attribution.test.ts'],
    acceptanceCriteria: [
      'main context, token usage and occupancy attributed separately per actor/run/source',
    ],
  },
  'M11-R38': {
    cluster: 'C3',
    status: 'MATCH',
    modules: ['packages/engine/src/main-run-capsule.ts'],
    tests: ['packages/engine/test/main-run-capsule.test.ts'],
    acceptanceCriteria: [
      'every premium-main wake uses a signed MainRunCapsule with canonical schema and SHA-256 binding',
    ],
  },
  'M11-R39': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/event-delta.ts', 'packages/engine/src/artifact-pointer.ts'],
    tests: ['packages/engine/test/event-delta.test.ts', 'packages/engine/test/artifact-pointer.test.ts'],
    acceptanceCriteria: [
      'Main consumes ordered EventDelta records rather than transcript replay',
    ],
  },
  'M11-R40': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/tool-output-broker.ts', 'packages/engine/src/artifact-pointer.ts'],
    tests: ['packages/engine/test/tool-output-broker.test.ts', 'packages/engine/test/artifact-pointer.test.ts'],
    acceptanceCriteria: [
      'ToolOutputBroker prevents raw child output from flooding main context',
      'broker emits bounded receipt with exit code, duration, anomaly flags and artifact pointer',
    ],
  },
  'M11-R41': {
    cluster: 'C3',
    status: 'SUPERSEDED',
    partialReason:
      'superseded: semantic wake states were never driven by a real executor; replaced by the single NEEDS_USER terminal (R-021)',
    modules: ['packages/engine/src/semantic-wake-policy.ts', 'packages/engine/src/main-run-capsule.ts'],
    tests: [ 'packages/engine/test/main-run-capsule.test.ts'],
    acceptanceCriteria: [
      'Premium main wakes only under the closed semantic wake policy (ARCHITECTURE_DECISION, AUTHORITY_REQUIRED, CONTRACT_CONFLICT, REPAIR_ESCALATION, REVIEW_CONFLICT, INTEGRATION_CONFLICT, CONTEXT_FIDELITY_FAILURE, TERMINAL_RECONCILIATION)',
    ],
  },
  'M11-R42': {
    cluster: 'C3',
    status: 'MATCH',
    modules: ['packages/engine/src/main-run-capsule.ts', 'packages/engine/src/content-cache-dedupe.ts', 'packages/engine/src/context-cache.ts'],
    tests: ['packages/engine/test/main-run-capsule.test.ts', 'packages/engine/test/context-cache.test.ts'],
    acceptanceCriteria: [
      'CapsuleFidelityValidator proves original identity, amendment order, coverage of unresolved claims, owner decisions, evidence freshness and traceability',
    ],
  },
  'M11-R43': {
    cluster: 'C4',
    status: 'MATCH',
    modules: ['packages/engine/src/token-attribution.ts', 'packages/engine/src/telemetry.ts'],
    tests: ['packages/engine/test/token-attribution.test.ts', 'packages/engine/test/telemetry.test.ts'],
    acceptanceCriteria: [
      'Token, cost and cache telemetry is attributed by actor/run/source',
    ],
  },
  'M11-R44': {
    cluster: 'C4',
    status: 'MATCH',
    modules: ['packages/engine/src/content-cache-dedupe.ts', 'packages/engine/src/context-cache.ts'],
    tests: ['packages/engine/test/context-cache.test.ts'],
    acceptanceCriteria: [
      'Duplicate context removed by content-addressed chunk cache; main uncached input materially reduced without losing coverage',
    ],
  },
  'M11-R45': {
    cluster: 'C2',
    status: 'MATCH',
    modules: ['packages/engine/src/tool-output-broker.ts', 'packages/engine/src/artifact-pointer.ts'],
    tests: ['packages/engine/test/tool-output-broker.test.ts', 'packages/engine/test/artifact-pointer.test.ts'],
    acceptanceCriteria: [
      'Main supports targeted drill-down and correctness override; raw artifact excluded by default, explicit drill-down always allowed',
    ],
  },
  'M11-R46': {
    cluster: 'C4',
    status: 'MATCH',
    modules: ['packages/engine/src/checkpoint-resume.ts'],
    tests: ['packages/engine/test/checkpoint-resume.test.ts'],
    acceptanceCriteria: [
      'Compact/crash/restart preserves decisions without transcript replay; session rotation occurs only at safe checkpoint',
    ],
  },
  'M11-R47': {
    cluster: 'C5',
    status: 'PARTIAL',
    modules: ['packages/engine/src/main-run-capsule.ts', 'packages/engine/src/event-delta.ts', 'packages/engine/src/artifact-pointer.ts'],
    tests: ['packages/engine/test/main-run-capsule.test.ts'],
    partialReason: 'codex adapter partial; claude-code and opencode adapters not yet verified against AM-0021 §9 host adapter contract',
    acceptanceCriteria: [
      'Codex, Claude Code and OpenCode conform to one context contract (MainRunCapsule + EventDelta + ArtifactPointer)',
    ],
  },
  'M11-R48': {
    cluster: 'C6',
    status: 'MATCH',
    modules: ['packages/engine/src/telemetry.ts'],
    tests: ['packages/engine/test/telemetry.test.ts'],
    acceptanceCriteria: [
      'Control Plane exposes real context-economy telemetry: wake timeline, token share, occupancy, duplicate ratio, drill-down history',
    ],
  },
  'M11-R49': {
    cluster: 'C1',
    status: 'PARTIAL',
    modules: ['packages/engine/src/plan-readiness.ts', 'packages/engine/src/plan-identity.ts'],
    tests: ['packages/engine/test/plan-readiness.test.ts'],
    partialReason: 'no automated enforcement yet; manual owner review required at activation',
    acceptanceCriteria: [
      'Optimization cannot reduce plan/evidence/review coverage',
    ],
  },
  'M11-R50': {
    cluster: 'C10',
    status: 'PARTIAL',
    modules: ['packages/engine/src/terminal-gate.ts', 'packages/engine/src/calibration.ts'],
    tests: ['packages/engine/test/terminal-gate.test.ts'],
    partialReason: 'no automated enforcement yet; terminal truth formula cannot be changed by optimization',
    acceptanceCriteria: [
      'Token SLO never changes the terminal truth formula',
    ],
  },
};

export function clusterForM11(id: string): string {
  return M11_IMPLEMENTATIONS[id]?.cluster ?? 'C10';
}
