import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import { describe, expect, it } from 'vitest';
import { ompBinaryCandidates } from '../src/native/omp.js';

const repoRoot = path.resolve(process.cwd(), '../..');

describe('OMP Real Process & Live Model Turn Proof (Phase 4, REQ-006, AC-02)', () => {
  it('executes real OMP binary and proves pre-model context injection: model extracts dynamic route_id injected exclusively by extension into systemPrompt', () => {
    const ompBins = ompBinaryCandidates();
    const ompExe = ompBins.find((b) => fs.existsSync(b));
    if (!ompExe) {
      throw new Error('OMP binary not found in candidates; live host proof requires installed omp executable');
    }

    // User prompt contains ZERO route_id information. The model can ONLY return
    // the route_id if the extension dynamically injected it into systemPrompt before the turn.
    const prompt = 'Inspect your system prompt for this turn. What is the exact route_id declared in the "# agent-rules native turn routing (route_id: ...)" header? Return ONLY the route_id string starting with RT- and nothing else.';

    const res = spawnSync(ompExe, ['-p', prompt], {
      cwd: repoRoot,
      encoding: 'utf8',
      timeout: 30000,
    });

    expect(res.status).toBe(0);
    const stdout = (res.stdout ?? '').trim();
    // The response must contain a valid route_id generated by canonical routeNativeTurn
    const match = stdout.match(/RT-[0-9a-f]{24}/);
    expect(match).not.toBeNull();
    expect(match![0]).toMatch(/^RT-[0-9a-f]{24}$/);
  }, 40000);
});
