model = "gpt-5.5"
model_reasoning_effort = "high"

[marketplaces.openai-bundled]
last_updated = "2026-05-30T10:54:18Z"
source_type = "local"
source = '\\?\C:\Users\DELL\.codex\.tmp\bundled-marketplaces\openai-bundled'

[marketplaces.openai-primary-runtime]
last_updated = "2026-05-30T11:30:41Z"
source_type = "local"
source = '\\?\C:\Users\DELL\.cache\codex-runtimes\codex-primary-runtime\plugins\openai-primary-runtime'

[plugins."documents@openai-primary-runtime"]
enabled = true

[plugins."spreadsheets@openai-primary-runtime"]
enabled = true

[plugins."presentations@openai-primary-runtime"]
enabled = true

[plugins."browser@openai-bundled"]
enabled = true

[features]
js_repl = false

[mcp_servers.node_repl]
command = 'C:\Users\DELL\AppData\Local\OpenAI\Codex\bin\3c238e29bbc930ff\node_repl.exe'
startup_timeout_sec = 120.0

[mcp_servers.node_repl.env]
BROWSER_USE_AVAILABLE_BACKENDS = "chrome,iab"
BROWSER_USE_CODEX_APP_BUILD_FLAVOR = "prod"
CODEX_CLI_PATH = 'C:\Users\DELL\AppData\Local\OpenAI\Codex\bin\958d608b5e0546a5\codex.exe'
CODEX_HOME = 'C:\Users\DELL\.codex'
NODE_REPL_INSTRUCTIONS_USE_CASE_BROWSER = "Control the in-app browser in conjunction with the Browser Plugin."
NODE_REPL_INSTRUCTIONS_USE_CASE_CHROME = "Control the Chrome browser in conjunction with the Chrome Plugin. Prefer this method of controlling Chrome over alternatives (such as Computer Use) unless the user explicitly mentions an alternative."
NODE_REPL_NATIVE_PIPE_CONNECT_TIMEOUT_MS = "1000"
NODE_REPL_NODE_MODULE_DIRS = ""
NODE_REPL_NODE_PATH = 'C:\Users\DELL\AppData\Local\OpenAI\Codex\bin\5b9024f90663758b\node.exe'
NODE_REPL_TRUSTED_BROWSER_CLIENT_SHA256S = "0b0d41e7a14a4903d2f95b0b3f427ed796b12c8edca2fa392a03df43997075ae,e13c388c2427308a68dffc803e1f28316077b719672e4518a621ae6ab56ad7cf"
NODE_REPL_TRUSTED_CODE_PATHS = 'C:\Users\DELL\.codex'

[mcp_servers.pencil]
command = 'C:\Program Files\Pencil\resources\app.asar.unpacked\out\mcp-server-windows-x64.exe'
args = ["--app", "desktop", "--agent", "codexCLI"]

[mcp_servers.gitnexus]
command = 'C:\Users\DELL\AppData\Roaming\npm\gitnexus.cmd'
args = ["mcp"]

[desktop]
conversationDetailMode = "STEPS_COMMANDS"
ambient-suggestions-enabled = false

[desktop.open-in-target-preferences]
global = "antigravity"

[desktop.open-in-target-preferences.perPath]
'P:\Fabsolution' = "antigravity"
'P:\tah-app-5f' = "antigravity"

[windows]
sandbox = "elevated"

[projects.'c:\users\dell\documents\codex\2026-05-29\hello']
trust_level = "trusted"

[projects.'p:\fabsolution']
trust_level = "trusted"

[projects.'c:\users\dell\documents\codex\2026-05-29\initforge-agent-rules-https-github-com']
trust_level = "trusted"

[projects.'p:\tah-app-5f']
trust_level = "trusted"

[projects.'c:\users\dell\documents\codex\2026-05-30\setup-behavior-c-a-chatgpt-sao']
trust_level = "trusted"

[projects.'c:\users\dell\documents\codex\2026-05-30\check-c-c-b-n-commit']
trust_level = "trusted"
